service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs6.11
  environment:
    MESSAGE: "I am ${opt:stage}"

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: /
          method: get
          cors: true

